
Activating Modules:
  1) defaultenv/10     2) lmod/7.5.13

The following have been reloaded with a version change:
  1) python/3.8 => python/3.6

[m8-17-14.rc.byu.edu:137709] mca: base: component_find: unable to open /apps/openmpi/1.10.7/gnu-4.8.5/lib/openmpi/mca_ess_pmi: libpmi.so.0: cannot open shared object file: No such file or directory (ignored)
[m8-17-14.rc.byu.edu:137709] mca: base: component_find: unable to open /apps/openmpi/1.10.7/gnu-4.8.5/lib/openmpi/mca_db_pmi: libpmi.so.0: cannot open shared object file: No such file or directory (ignored)
[m8-17-14.rc.byu.edu:137709] mca: base: component_find: unable to open /apps/openmpi/1.10.7/gnu-4.8.5/lib/openmpi/mca_grpcomm_pmi: libpmi.so.0: cannot open shared object file: No such file or directory (ignored)
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 67, in <module>
    from schwimmbad import MPIPool
ModuleNotFoundError: No module named 'schwimmbad'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 67, in <module>
    from schwimmbad import MPIPool
ModuleNotFoundError: No module named 'schwimmbad'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 67, in <module>
    from schwimmbad import MPIPool
ModuleNotFoundError: No module named 'schwimmbad'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 67, in <module>
    from schwimmbad import MPIPool
ModuleNotFoundError: No module named 'schwimmbad'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 67, in <module>
    from schwimmbad import MPIPool
ModuleNotFoundError: No module named 'schwimmbad'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 67, in <module>
    from schwimmbad import MPIPool
ModuleNotFoundError: No module named 'schwimmbad'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 67, in <module>
    from schwimmbad import MPIPool
ModuleNotFoundError: No module named 'schwimmbad'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 67, in <module>
    from schwimmbad import MPIPool
ModuleNotFoundError: No module named 'schwimmbad'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 67, in <module>
    from schwimmbad import MPIPool
ModuleNotFoundError: No module named 'schwimmbad'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 67, in <module>
    from schwimmbad import MPIPool
ModuleNotFoundError: No module named 'schwimmbad'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 67, in <module>
    from schwimmbad import MPIPool
ModuleNotFoundError: No module named 'schwimmbad'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 67, in <module>
    from schwimmbad import MPIPool
ModuleNotFoundError: No module named 'schwimmbad'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 67, in <module>
    from schwimmbad import MPIPool
ModuleNotFoundError: No module named 'schwimmbad'
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[15283,1],7]
  Exit code:    1
--------------------------------------------------------------------------
